In [94]:
# Гаврилов Олег. Домашнее задание 1

In [1]:
import numpy as np

In [84]:
# формируем исходную матрицу

m, n = 3, 5
A = np.zeros([m, n])
for i in range(m):
    for j in range(n):
        A[i, j] = i + j + 1

In [85]:
# вычисляем сокращённое SVD, зная что ранг матрицы A всегда равен 2

U, s, V = np.linalg.svd(A, full_matrices=False)
U = U[:, :2]; s = s[:2]; V = V[:2, :]

In [62]:
U

array([[-0.44127483,  0.79913069],
       [-0.56800242,  0.10347264],
       [-0.69473   , -0.59218541]])

In [63]:
s

array([16.7010311 ,  1.03709214])

In [64]:
V

array([[-0.21923614, -0.32126621, -0.42329627, -0.52532633, -0.6273564 ],
       [-0.74292363, -0.44360796, -0.1442923 ,  0.15502336,  0.45433903]])

In [68]:
U @ np.diag(s) @ V

array([[1., 2., 3., 4., 5.],
       [2., 3., 4., 5., 6.],
       [3., 4., 5., 6., 7.]])

In [83]:
# проверим, что SVD вычислено правильно (норма разности должна быть мала)

np.linalg.norm(A - U @ np.diag(s) @ V)

8.722849276405927e-15

In [78]:
# норма Фробениуса

np.linalg.norm(A)

16.73320053068151

In [90]:
# корень из суммы квадратов всех элементов

np.sqrt(np.sum(A*A))

16.73320053068151

In [81]:
# спектральная норма

np.linalg.norm(A, ord=2)

16.701031102734284

In [91]:
# максимальное сингулярное число

s[0]

16.701031102734284

In [92]:
s[0] + s[1]

17.738123242084473

In [93]:
np.trace(A @ A.T)

280.0